#! /bin/bash

clear
echo "Please wait..."
# 個人環境初期化用
bash /home/user/bin/init.sh

# for Check
# grep -A5 -n "UnderSteer" /proc/bus/input/devices

cd "$(dirname "$0")"
#pwd

# もしSUDO失敗したらスクリプト終了
# sudo権限をチェック（パスワード入力も要求）
sudo -v || exit 1
#------------------------------------

sudo chmod 666 /dev/uinput

sudo pkill -f understeer.py

clear

bash ./steamOption.sh
if [ $? -eq 0 ]; then
    echo "..."
else
    echo "ハンドルコントローラを接続してください。"
    echo "Connect the steering wheel controller."
    echo ""
    echo "Press Enter Key to Exit."
    read ok
    exit 1
fi


echo ""
echo "You can select \"Force feedback mode:\""
echo ""
echo "Please Select"
echo ""
echo "1) WITHOUT Force Feedback mode"
echo "Enter) with FFB mode"
read ff
mode=""
if [ "$ff" = "1" ]; then
    mode="-easy"
fi

echo "1) Test Drive Unlimited Solar Crown       (FFB OK)"
echo "2) rFactor2                               (未チェック)"
echo "3) City Car Driving                       (未チェック)"
echo "4) Project Cars 2                         (未チェック)"
echo "5) Forza Horizon 5                        (FFB OK)"
echo "6) Euro Truck                             (FFB OK)"

echo "11) Asseto Corsa           (FFB cannot? 未チェック)"
echo "12) Dirt Rally             (未対応effect: FRICTION(84) )"
echo ""
echo "Please Select.. (case sensitive)"
read sel

flg="Def"

if [ "$sel" = "1" ]; then
  echo "# 1249970 # Test Drive Unlimited Solar Crown"
  flg="T"
  steam steam://rungameid/1249970 >/dev/null 2>&1 &
  # --gear-map gears.dat        ニュートラル入力が別途必要な場合に指定
  # --keymap keymapTDUSC.dat    キーボードに入力を転送したい場合
  sudo python3 understeer.py --ff-pass-through --gear-map gears.dat \
                                      --keymap keymapTDUSC.dat  
fi

if [ "$sel" = "2" ]; then
  echo "# 365960 # rFactor2"
  flg="T"
  steam steam://rungameid/365960 >/dev/null 2>&1 &
  # --gear-map gears.dat        ニュートラル入力が別途必要な場合に指定
  sudo python3 understeer.py --gear-map gears.dat --ff-pass-through$mode  
fi

if [ "$sel" = "3" ]; then
  echo "# 493490 # City Car Driving"
  flg="T"
  steam steam://rungameid/493490 >/dev/null 2>&1 &
  # --gear-map gears.dat        ニュートラル入力が別途必要な場合に指定
  sudo python3 understeer.py --gear-map gears.dat --ff-pass-through$mode  
fi

if [ "$sel" = "4" ]; then
  echo "# 378860 # Project Cars 2"
  flg="T"
  steam steam://rungameid/378860 >/dev/null 2>&1 &
  sudo python3 understeer.py --ff-pass-through$mode --no-grab 
fi

# ----------------------

if [ "$sel" = "5" ]; then
  echo "# 1551360 # Forza Horizon 5"
  flg="T"
  steam steam://rungameid/1551360 >/dev/null 2>&1 &
  # --keymap keymapFH5.dat      キーボードに入力を転送したい場合
  sudo python3 understeer.py --ff-pass-through$mode --keymap keymapFH5.dat 
fi

if [ "$sel" = "6" ]; then
  echo "# 227300 # Euro Truck"
  flg="T"
  steam steam://rungameid/227300 >/dev/null 2>&1 &
  # --gear-map gears.dat        ニュートラル入力が別途必要な場合に指定
  sudo python3 understeer.py --gear-map gears.dat --ff-pass-through$mode 
fi



if [ "$sel" = "11" ]; then
  echo "# 244210 # Asseto Corsa"
  flg="T"
  steam steam://rungameid/244210 >/dev/null 2>&1 &
  sudo python3 understeer.py --ff-pass-through$mode  
fi


if [ "$sel" = "12" ]; then
  echo "# 310560 # Dirt Rally"
  flg="T"
  steam steam://rungameid/310560 >/dev/null 2>&1 &
  sudo python3 understeer.py --ff-pass-through$mode  
fi



# -------------------

# ここだけフラグチェック
if [ "$flg" = "Def" ]; then
    clear
    echo ""
    echo "n) Only Understeer no FFB"
    echo "t) Only Understeer with FFB (with TRACE-MSG)"
    echo "d) Only Understeer with FFB (with DEBUG-MSG)"
    echo "i) Only Understeer with FFB (with INFO-MSG)"
    echo "f) Only Understeer with FFB (no DBG-MSG)"
    echo "e) Only Understeer with easy-FFB"
    echo ""
    echo "o) --ff-off Test"
    echo ""
    echo "Enter) Only Understeer with FFB (no Grab with DBG-MSG)"
    echo ""
    echo "Please Select.. (case sensitive)"
    read sel
fi

if [ "$sel" = "n" ]; then
  echo "# Only Understeer no FFB"
  flg="T"
  sudo python3 understeer.py --no-grab 
fi

if [ "$sel" = "t" ]; then
  echo "# Only Understeer with FFB (with DBG-MSG)"
  flg="T"
  sudo python3 understeer.py --ff-pass-through --no-grab  -vvv
fi

if [ "$sel" = "d" ]; then
  echo "# Only Understeer with FFB (with DBG-MSG)"
  flg="T"
  sudo python3 understeer.py --ff-pass-through --no-grab  -vv
fi

if [ "$sel" = "i" ]; then
  echo "# Only Understeer with FFB (with INFO-MSG)"
  flg="T"
  sudo python3 understeer.py --ff-pass-through --no-grab  -v
fi

if [ "$sel" = "f" ]; then
  echo "# Only Understeer with FFB (no MSG)"
  flg="T"
  sudo python3 understeer.py --ff-pass-through --no-grab
fi

if [ "$sel" = "e" ]; then
  echo "# Only Understeer with easy-FFB (no MSG)"
  flg="T"
  sudo python3 understeer.py --ff-pass-through-easy --no-grab 
fi

if [ "$sel" = "o" ]; then
  echo "# Test --ff-off"
  flg="T"
  sudo python3 understeer.py --ff-pass-through --no-grab --ff-off  
fi

# -------------------

# ここだけフラグチェック
if [ "$flg" = "Def" ]; then

  echo "# Only Understeer with FFB (Grab no MSG)"
  flg="T"
  sudo python3 understeer.py --ff-pass-through 

fi

echo ""
echo "for Debug.."
echo "Press Enter to EXIT"
read ok
